// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	ws "socialAPI/internal/api/chat/ws"

	mock "github.com/stretchr/testify/mock"
)

// Hub is an autogenerated mock type for the Hub type
type Hub struct {
	mock.Mock
}

// BroadcastMessage provides a mock function with given fields: msg
func (_m *Hub) BroadcastMessage(msg ws.Message) {
	_m.Called(msg)
}

// RegisterClient provides a mock function with given fields: client
func (_m *Hub) RegisterClient(client *ws.Client) {
	_m.Called(client)
}

// Run provides a mock function with no fields
func (_m *Hub) Run() {
	_m.Called()
}

// UnregisterClient provides a mock function with given fields: client
func (_m *Hub) UnregisterClient(client *ws.Client) {
	_m.Called(client)
}

// NewHub creates a new instance of Hub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hub {
	mock := &Hub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
